### ISSUE TITLE
Store both initial order size and remaining size on order

### ISSUE THREAD

**Issue by bogberry** [econia-labs/econia#145]
Most exchange APIs include both size and remaining size when retrieving information about orders, where size refers to the size the user specified when they placed or last modified the order.

With the existing Move code, size is not stored, so it is impossible to build an API on top of Econia that offers this information. In future versions, it would be better to have this information, especially since the increase in free storage on Aptos means that there will likely not be much of a gas penalty for this.

**Comment by alnoki** [comment]
Addressed at https://github.com/econia-labs/econia-v5/blob/cb8b990/doc/architecture-specification.md#orders
