### ISSUE TITLE
Emit maker events and taker events to user account, not orderbook account

### ISSUE THREAD

**Issue by bogberry** [econia-labs/econia#146]
Currently, the event handle for both maker events and taker events are included as part of the `OrderBook` struct, and are stored with the orderbook Aptos account. This makes it difficult for any user that is not using an API and is interacting directly with the smart contract to put together their order history.

This could be made much easier if the event handles were moved to a resource on the user's account, in which case they would only have to parse through the events that are relevant to them.

**Comment by alnoki** [comment]
Closing per event v2 model and deprecation of handle-based events
