### ISSUE TITLE
Test fail to pass due to dependency err

### ISSUE THREAD

**Issue by move-girl** [econia-labs/econia#15]
`aptos move test` / `move test` both fail with following err.
┌── test_withdraw_collateral_user_override ──────
│ ITE: An unknown error was reported. Location:
│ VMError (if there is one): VMError {
│     major_status: UNEXPECTED_VERIFIER_ERROR,
│     sub_status: None,
│     message: Some(
│         "Unexpected verifier/deserialization error! This likely means there is code stored on chain that is unverifiable!\nError: VMError { major_status: MISSING_DEPENDENCY, sub_status: None, message: None, exec_state: None, location: Module(ModuleId { address: 0000000000000000000000000000000000000000000000000000000000000001, name: Identifier(\"signature\") }), indices: [(FunctionHandle, 0)], offsets: [] }",
│     ),
│     exec_state: None,
│     location: Module(
│         ModuleId {
│             address: 0000000000000000000000000000000000000000000000000000000000000001,
│             name: Identifier(
│                 "signature",
│             ),
│         },
│     ),
│     indices: [
│         (
│             FunctionHandle,
│             0,
│         ),
│     ],
│     offsets: [],
│ }
└──────────────────
Test result: FAILED. Total tests: 149; passed: 58; failed: 91
Output of `aptos move --version` is `aptos-move 0.2.2`

**Comment by move-girl** [comment]
@alnoki @xorkiki @Manahip anyone could give some help?

**Comment by alnoki** [comment]
@move-girl are you on `main/head`? I actually just replied to the other issue you submitted (#16 ) regarding tests with the output from a successful run and a tip that might help you run it on your machine.

You might also try re-building the `aptos` CLI [as described in the readme](https://github.com/econia-labs/econia#command-line-setup)
