### ISSUE TITLE
Issue order ID for all orders, not just maker orders

### ISSUE THREAD

**Issue by alnoki** [econia-labs/econia#311]
Presently, Econia only assigns an order ID to the portion of a limit order that posts as a maker order.

This order ID is unique within a market, but not across markets (to ensure parallelism).

It is suggested that a parallelizeable globally unique ID be assigned to each order regardless of how much it makes or takes.

**Comment by bogberry** [comment]
I don't think the ID needs to be unique across markets? We just need an ID that is assigned to all orders regardless of whether they are maker or taker orders. I don't think using the same ID in different market poses an issue

**Comment by alnoki** [comment]
> I don't think the ID needs to be unique across markets? We just need an ID that is assigned to all orders regardless of whether they are maker or taker orders. I don't think using the same ID in different market poses an issue

Good point, sequentiality within a given market could also help with iteration

**Comment by alnoki** [comment]
Marking as closed per v4.1.0 revisions
