### ISSUE TITLE
Constants are sorted alphabetically and not by category

### ISSUE THREAD

**Issue by bogberry** [econia-labs/econia#390]
Constants defined here are sorted alphabetically, and not by category. Many of these constants are effectively enum variants, so variants belonging to the same enum should be placed together. 

https://github.com/econia-labs/econia/blob/e6c85bd2248c08a54452f9e761a34b4e0a1ef0d4/src/move/econia/sources/market.move#L857-L938

For example, there is no indication that `FILL_OR_ABORT` and `IMMEDIATE_OR_CANCEL` belong together. If one were to add a new variant to this enum, it's hard to tell what values have already been used.

**Comment by alnoki** [comment]
Closing per https://github.com/econia-labs/econia-v5/blob/cb8b990c5bc4ee67118eab73e4dab32343695596/src/move/econia/sources/core.move#L16-L27
