### ISSUE TITLE
Canonicalize markets & add concentrated liquidity provision

### ISSUE THREAD

**Issue by elliottdehn** [econia-labs/econia#451]
# What
Canonical markets mean this: two coin types, in either order, associate with one order book and/or liquidity pool.

This means there can be no market parameters such as lot size, tick size, or minimum order size--easily the most difficult to eliminate. Obtaining canonical markets has the enormous benefit of allowing protocols to plug-and-play the exchange. Protocols are important because they represent an increase in Econia's surface area beyond what's possible for us to develop.

I believe that I have formulated and at least partially developed an exchange design with canonical markets that can rigorously claim to be protected from "order stuffing" attacks. In the threat model, I assume an infinite incentive to halt trading and infinite resources available to do so. In my model, the objective is to ensure trading can always proceed forward in useful capacity regardless of the state of the order book.

# Design

Much like Uniswap V3, the order book is broken up into "ticks" which are spaced 0.01% apart in terms of price. These ticks are further broken down into 128 "buckets" each using linear interpolation between the highest and lowest price for the tick. Buckets are mutually exclusive of order type, meaning ASK orders can't be placed into a bucket on the BID side.

Each bucket has a price width of 1/128th of 0.01%, or what I've been calling a "mill" in private. Orders within the same bucket are considered to be close enough together that it's reasonable to execute them in order of size (the product of base and quote asset amounts) instead of price and/or time. We keep track of the total amount of assets inside the bucket and if the trade exceeds them, the bucket's open orders are discarded all together.

Let's examine a perfect attacker's options. Remember: the attacker's only goal is to halt useful trading.

The attacker's best option to halt trading is by stuffing one bucket with thousands of small orders to make it impossible for a single trade to execute across the bucket. We recall that each bucket keeps track of the total amount of assets inside of it, and the attacker will fail to escape the "total execution" mechanism should he only stuff the bucket with small orders. Therefore, he must insert larger orders too in order to drive the bucket size up beyond most trade sizes and indeed prevent a total execution of all his orders from occurring. However, he'll find that these more voluminous orders are executed before his small orders--and unlike the small orders, these order have sizes that are useful! Our attacker will find that his attempt to "stuff" the bucket with volume will simply result in ordinary trading. Once these voluminous orders are cleared out, the bucket's volume will drop to a point where total execution is possible.

Ordinary trading is never halted regardless of how many orders there are, or how much money the attacker has.

We haven't gotten into liquidity provision, but in my implementation it works much the same way as in Uniswap V3 (the code has been mostly ported over). There aren't as many issues to consider with liquidity provision, so it's easier apart from the math.

# Drawbacks

Orders are executed in order of price, down to a 1/128th of 0.01% granularity, and then by size. This is considered okay because within a bucket, prices are so close together that beating an order on price doesn't _mean_ much. We're basically saying: if you want to gain price priority, it has to be by at least 1/128th of 0.01% _or_ you can use a larger trade.

There is an argument that providing benefits to larger-volume stakeholders may be advisable because this means bigger liquidity will be more attracted to the book.

Time priority is not considered important as it only applies when prices are equal which is rare, and executing by time priority within a bucket would allow the order book to be attacked easily. Executing by price priority within a bucket would do the same, with not much benefit other than people playing price leap-frogging games that mean nothing.

# Implementations

I've implemented (but not tested) the data structure that would be used to store orders within a bucket ordered by size: [here](https://gist.github.com/elliottdehn/495398c0d6949966c424f7552417cade).

I've implemented (and tested a little) the order book described above, minus the total execution mechanism: [here](https://gist.github.com/elliottdehn/3dc53e4a4ee64e2d1dd329643ef9e61b).

I've implemented the math for calculating relevant amounts by porting over the Uniswap code, which was non-trivial. Take a look at the "pure" operations [here](https://gist.github.com/elliottdehn/3dc53e4a4ee64e2d1dd329643ef9e61b#file-pure-move-L1).

# Considerations

It's surely possible to compose the order book as just two binary trees containing bids and asks, each ordered by price. However, this arrangement is vulnerable to an order book attack: we have no ability to perform total executions, so we must execute every order one-by-one. Regardless of how intelligent our data structure is, it's unworkable to touch ("read") every order that gets executed in all cases for now-obvious reasons.

**Comment by alnoki** [comment]
Closing per https://github.com/econia-labs/econia-v5/blob/cb8b990/doc/architecture-specification.md#units
