### ISSUE TITLE
Calibrate genesis incentive parameters for practical activity

### ISSUE THREAD

**Issue by alnoki** [econia-labs/econia#49]
# Registration fees

The primary purpose of market, underwriter, and custodian registration fees is to deter DoS attacks against the registry. Hence these fees shall be calibrated such that they discourage excessive malicious activity, but that they are not so high as to prevent legitimate use, even experimentation in some cases. Indexing is also a factor.

Markets, for instance, are stored in a doubly linked list that is iterable off-chain. While market registration events are emitted for market registration, each additional registered market increases the number of queries required to index the entire registry. Additionally, excessive registration of quasi-duplicate markets with similar lot/tick size parameters may lead to confusion and fracturing of liquidity. Hence a proposed market registration fee is set to \$ 25.

As for custodian capabilities, if an dApp wants to enable margin trading, etc., they will want to self-issue custodian a custodian capability and use it to manage user's market accounts. Rather than having a dApp use a single custodian capability for multiple market accounts, however, it should be encouraged to issue multiple ones for each market account so as to encourage parallelism. Since the custodian capability issuance number is simply a `u64`, the cost to register a custodian capability need not be so high as to discourage extra indexing costs, for instance. Hence a proposed custodian registration fee is \$ 1 USD.

Similarly, to allow multiple underwriter capabilities for different markets, it is proposed that underwriter registration fees be set at \$ 1 USD

# Taker fees

Taker fees are the primary revenue driver for both integrators and Econia. To ensure adequate proceeds, a flat taker fee of 0.05% is proposed.

# Integrator tiers

The percentage of fees reserved for integrators at a given tier, and the cost to activate to a given tier combine to produce a break-even volume. For example, if tier 0 entitles integrators to 0.01% fees, tier 2 entitles them to 0.015% fees, and it costs \$ 5,000 USD to activate to tier 2, then the break-even price on the activation fee is $5000 / ((0.015 - 0.01) / 100) = 100000000$, or \$ 100 M volume routed through Econia. Here $100000000 * (0.05 - 0.015) / 100 = 35000$ or \$35 k USD of fees are then diverted to an `EconiaFeeStore`. Note that what happens to the Econia fee share is still undetermined: at protocol launch, the Econia fee share will simply sit and collect.

The cost to withdraw from an integrator fee store is a deterrent against frequent and excessive withdrawals, as these will collide with the matching engine and inhibit parallelism. But charging to withdraw is still a pain point for integrators, and so withdrawal fees should be kept reasonably low. Hence withdrawal fees on the order of \$ 1 to \$2 USD are proposed.

Hence in nominal values, the following integrator parameters are proposed:

| Tier | Fee share (%)   | Activation Fee (USD) | Break even volume (USD) | Econia fee share at break even (USD) | Withdrawal fee (USD) |
|------|-----------------|----------------------|-------------------------|--------------------------------|----------------------|
| Base | 0.01            | 0                    | -                       | -                              | 2                    |
| 1    | 0.0125          | 250                  | 10 M                    | 3750                           | 1.50                 |
| 2    | 0.015           | 5000                 | 100 M                   | 35000                          | 1.25                 |
| 3    | 0.0175          | 75000                | 1 B                     | 325000                         | 1.00                 |

As of the time of this writing, one `APT` costs \$ 4.41, and rounding to a price of \$4 yields a resultant number of round subunits that can be hard-coded as genesis parameters.

# Market conditions

Note, however, that if the `USD`-denominated price of `APT` (the utility coin) increases or decreases, the actual costs to activate, etc. will shift. Since percentage terms will not shift, this means that the break even volume will increase proportional to the `APT` price increase.

Notably, if the `APT/USD` were to 10x, then it may be proposed to lower utility-coin denominated costs. Here, the following scenario is possible (with hypothetical, yet demonstrative values):

* Tier activate costs are 100/1000/10000 to tier 1/2/3
* An integrator pays 1000 to activate to tier 2.
* `USD`-denominated `APT` price goes up 10x
* Tier costs are shifted to 10/100/1000.
* The same integrator has to pay 900 to activate to tier 3, even though they have already paid 1000.

Note, however, that in this case, the integrator still pays an equivalent `USD` amount: they would have had to pay 9000 before the price volatility, and they have to pay 900 after the 10x price volatility.

Hence as long as utility coin fee amounts are monitored and updated for price shifts (including inflation?), this discrepancy in utility coins paid is addressed.

Alternatively, of course, utility coins paid thus far for an integrator fee store could be tracked, but they would have to be tracked in USD values, and this approach would introduce an oracle dependency. Hence the straightforward solution is to simply manually update the amounts as needed with market activity.

@fcremo

**Comment by BriungRi** [comment]
Market fees - I think these are fine and could even be higher since these are pretty low frequency operations

Custodian/Underwriter fees - I think these are actually a bit high. If you think the best practice for integrators is to have a custodian/underwriter per market account, this can get pretty expensive quickly. Perhaps the factors to consider (1) Threat model, who would DoS via this attack vector and (2) How much money could they use to deploy an attack and how long would it last (3) How much money do integrators expect to make per user

Taker fees - I don't have a strong opinion on this. I think this should remain customizable so that we can observe how this fee works in practice

Integration tiers - Only possible feedback here is that it might be good to have more tiers in between the existing ones to build good feedback loops with integrators. Otherwise, I also think this is something that should be monitored in production to see if these are the right incentive params.

**Comment by alnoki** [comment]
@BriungRi 

> Market fees - I think these are fine and could even be higher since these are pretty low frequency operations

Since market registration fees are mostly for DoS prevention, if you think they are sufficient than we will probably keep them where they are so as not to discourage registration of exotic markets. Given that a few dozen markets are likely going to be sufficient at first, market registration fees will constitute only a minor portion of net fees anyways.

> Custodian/Underwriter fees - I think these are actually a bit high. If you think the best practice for integrators is to have a custodian/underwriter per market account, this can get pretty expensive quickly. Perhaps the factors to consider (1) Threat model, who would DoS via this attack vector and (2) How much money could they use to deploy an attack and how long would it last (3) How much money do integrators expect to make per user

Good point on this. The thread model would basically be registering capabilities again and again to generate transaction collisions, and a max of 2^64 can be generated total. Hence no one is going to have enough money to make it so that no more capabilities can be registered, so the real threat is just clogging up the registry temporarily. Hence we can probably reduce this to something on the order of 1-10 cents per, because at the most a malicious actor will make it so that it takes slightly longer to register a market/capability. Even so, however, sustaining an attack like this at, say 2k tps, at 1 cent per capability, for 10 minutes costs $10 * 60 * 2000 * 0.01 = 12000$ USD anyways. So how about 0.01 USD for both underwriter and custodian capabilities?

> Taker fees - I don't have a strong opinion on this. I think this should remain customizable so that we can observe how this fee works in practice

Agreed

> Integration tiers - Only possible feedback here is that it might be good to have more tiers in between the existing ones to build good feedback loops with integrators. Otherwise, I also think this is something that should be monitored in production to see if these are the right incentive params.

Good point about more reward granularity. The only hangup here is that the number of tiers can only be increased with subsequent on-chain modifications, so if we do 7 genesis tiers, we can never go down to 6. We could of course just make tier 7 prohibitively expensive, having 6 in practice (or fewer, depending on how many we block out).

As for granularity, do you think we should stick to a logarithmic relationship with break even volume? E.g. 10k, 100k, 1M, 10M, 100M, 1B?

**Comment by BriungRi** [comment]
> So how about 0.01 USD for both underwriter and custodian capabilities?

This is much better. If we can also increase it in the future as needed that is always good.

> As for granularity, do you think we should stick to a logarithmic relationship with break even volume? E.g. 10k, 100k, 1M, 10M, 100M, 1B?

I think this is fine and 6 tiers here seems good enough.

**Comment by alnoki** [comment]
@BriungRi Sounds good. This is what it would look like:

* Market registration: $25 USD
* Custodian registration: $0.01 USD
* Underwriter registration: $0.01 USD

| Tier | Fee share (%)   | Activation Fee (USD) | Break even volume (USD) | Econia fee share at break even (USD) | Withdrawal fee (USD) |
|------|-----------------|----------------------|-------------------------|--------------------------------------|----------------------|
| Base | 0.01            | 0                    | -                       | -                                    | 0.2                  |
| 1    | 0.012           | 0.20                 | 10 k                    | 3.80                                 | 0.19                 |
| 2    | 0.013           | 3                    | 100 k                   | 37                                   | 0.18                 |
| 3    | 0.014           | 40                   | 1 M                     | 360                                  | 0.17                 |
| 4    | 0.015           | 500                  | 10 M                    | 3500                                 | 0.16                 |
| 5    | 0.016           | 6000                 | 100 M                   | 34000                                | 0.15                 |
| 6    | 0.017           | 70000                | 1 B                     | 333000                               | 0.14                 |

Note that the cost to withdraw has also been lowered across all tiers to be at most the cost to activate to tier 1.
