### ISSUE TITLE
Match `BUY/SELL` polarity to map to `BID/ASK`

### ISSUE THREAD

**Issue by alnoki** [econia-labs/econia#56]
Presently, `market.move` defines the following constants:

| Constant | Value     |
|----------|---------|
| `ASK`     |  `true`   |
| `BID`      |  `false`  |
| `BUY`     |  `true`   |
| `SELL`    |  `false`  |

`ASK` and `BID` are intended for maker activity, e.g. `place_limit_order()`, while `BUY` and `SELL` are intended for taker activity, e.g. `place_market_order()`. Hence per this schema `ASK = BUY` and `BID = SELL`, conveying that taker buys match against maker asks, and taker sells match against the maker bids.

However, also per this schema, if a user passes `ASK` during a taker function call, denoting that they want to sell, they will actually trigger a buy. Similarly, if a user passes `BID` during a taker function call, denoting that they want to buy, they will actually trigger a sell.

Hence it is proposed that `BUY` and `SELL` be modified to assume the following:

| Constant | Value     |
|----------|---------|
| `BUY`     |  `false`   |
| `SELL`    |  `true`  |

Note that `incentives.move` shall also be updated to reflect the constant modifications.

@mkurnikov

**Comment by BriungRi** [comment]
I did originally find `BID != BUY` to be confusing at first. Aligning `BID == BUY` should help future developers who are reading through Econia code.
