### ISSUE TITLE
have you publish your rust sdk to https://crates.io/

### ISSUE THREAD

**Issue by crazybits** [econia-labs/econia#668]
as subjected, please publish your rust sdk to https://crates.io/

**Comment by alnoki** [comment]
Tagging @CRBl69 for assistance with this

**Comment by alnoki** [comment]
@crazybits please see https://github.com/aptos-labs/aptos-core/issues/8984#issuecomment-1922007425: unfortunately we are blocked by Aptos Labs at the moment

**Comment by alnoki** [comment]
@crazybits per https://github.com/aptos-labs/aptos-core/issues/8984#issuecomment-1923604971 it looks like Aptos Labs isn't going to upload their crates (which are Econia dependencies) this any time soon, so I am closing the issue since we don't have any way to unblock the dependency
