### ISSUE TITLE
Consider price decimalization

### ISSUE THREAD

**Issue by alnoki** [econia-labs/econia#72]
# Background

Presently, Econia uses integer prices, denoted as the number of ticks per lot, with both lot size and tick size limited to integer multiples of indivisible asset subunits. This schema ensures that the amount of base and quote asset traded by market takers is constant, regardless of how many separate fills it takes to completely match an order: with an integer number of ticks filled for each lot, there is no opportunity for accumulated truncation errors. Hence base and quote ceiling fields are deterministic, and there is never any confusion about how much of an asset will be traded away or received by a market maker. In particular, this means that `market::Order.size` acts predictably.

# Limitations

Per the present schema, lot size and tick size granularity may be limited due to the number of decimal places in a quote asset. For example, `USDC` only has 6 decimals, which means the minimum total quote amount increment for an incremental increase in size or price must be an integer multiple of 0.000001 `USDC`. Hence, for a `wBTC/USDC` market, for example, at a tick size of 0.01 `USDC` (`Coin.value = 1`), the minimum lot size is 0.0001 `wBTC`. As of the time of this writing, one `BTC` costs approximately 17530.06, such that the minimum lot size ends up being some 1.7663006 `USD` nominal. Should this amount be considered insufficiently granular, lot size could be changed to 0.00005 `wBTC`, but then tick size would have to go up to 0.02 `USDC` (`Coin.value = 2`).

Moreover, consider a stable swap market like `USDT/USDC`, where one may wish to specify price down to as many as 8 decimal places, corresponding to 0.00000001 `USDC`. Here, the incremental total quote amount increase for an incremental increase in size or price cannot be represented in an integer multiple of indivisible coin subunits (`Coin.value < 1`), and thus is not possible in the current pricing paradigm.

# Decimal pricing

A proposed solution involves a "nominal decimal price" defined relative to the nominal quote coin amount. Continuing the above stable swap example, here a market registrant would pass `price_decimals: u8 = 8`, implying a tick size of 0.00000001 `USDC`, and prices would still be stored internally as a `u64` number of ticks: a price of 1.00012345 `USDC`, for example, would be represented internally (`Order.price` or similar) as $1.00012345 (10 ^ 8) = 100012345$. Hence with an internal integer representation for a decimal shift, prices could still be sorted for price-time priority.

As for calculating fill amounts on an order, a proposed solution involves calculating a total base and quote amount to fill when the order is placed, with optional truncation. Continuing the above example, assume `USDT` also has 6 decimals, and a maker places a buy order for 150 `USDT` at a price of 1.00012345 `USDC` per `USDT`:

* The total base amount is simply a coversion to indivisible coin subunits: $150 (10^6) = 150000000$
* The total quote amount, however, cannot be specified as an integer multiple of indivisible coin subunits, so truncate to 6 decimal places: $\lfloor (150)(1.00012345)(10^6) \rfloor = \lfloor 150.0185175 (10^6) \rfloor = 150018517$

Now the matching engine, which can fill up until a certain amount of base or quote is matched, simply fills both completely, or uses a proportion:

* If a taker has 150000000 `USDT` subunits and 150018517 `USDC` subunits to trade, the order completely fills.
* If a taker has only 140000000 `USDT` subunits to trade, the order fills 140000000 `USDT` subunits and `140000000 * 150018517 / 150000000` (integer truncation) `USDC` subunits, then the total base and quote amounts to fill are decremented accordingly. Hence a similar proportional operation can be used for future partial fills.

Regardless of how many fills it takes to match a limit order, the maker thus ends up receiving exactly as much base and quote as specified when they placed the order.

# Configurability

Per this schema, makers can specify any two of the following and calculate the third:

* Base to fill.
* Quote to fill.
* Limit price.

Here, there is no separate `size` argument required for limit orders, making it so that taker-only orders (swaps and market orders) and limit orders all use similar inputs: base, quote, and price.

Additionally, this approach does not preclude a minimum lot or tick size. For example, a market can still specify a minimum order size of `5 USDT`, and a lot size of 0.01 `USDT`, and user inputs will simply be checked during limit order placement, with aborts and truncations applied accordingly. As for tick size, prices could simply be corrected so as to constitute an integer multiple of ticks: with a `price_decimals: u8 = 8`, tick size could be defined as 0.00000025. Notably, however, only a minimum order size (specified in terms of base asset subunits) is essential to prevent many small orders from going up on the order book.

# Integer operations

For a given `price_decimals` and base/quote combination, a fixed conversion factor will necessary to convert between indivisible base and quote subunits at a given price:

| Term  | Meaning                    |
|-------|----------------------------|
| $d_b$ | Base decimals              |
| $d_q$ | Quote decimals             |
| $d_p$ | Price decimals             |
| $n_p$ | Nominal price (as decimal) |
| $n_b$ | Nominal base (as decimal)  |
| $n_q$ | Nominal quote (as decimal) |
| $i_p$ | Integer price              |
| $i_b$ | Integer base               |
| $i_q$ | Integer quote              |

Continuing the above example, consider a user placing an order for 150 `USDT` at a price of 1.00012345 `USDC` per `USDT`:

* $i_b = n_b 10^{d_b} = 150 (10^6) = 150000000$
* $i_p = n_p 10^{d_p} = 1.00012345 (10^8) = 100012345$
* $i_q = \lfloor n_q 10^{d_q} \rfloor = \lfloor n_b n_p 10^{d_q} \rfloor = \lfloor (150)(1.00012345)(10^6) \rfloor = 150018517$, or equivalently,
* $\Large i_q = \lfloor n_b n_p 10^{d_q} \rfloor = \lfloor \frac{i_b}{10^{d_b}} \frac{i_p}{10^{d_p}} 10^{d_q} \rfloor = \lfloor \frac{i_b i_p}{10^{(d_b + d_p - d_q)}} \rfloor = \lfloor \frac{(150000000) (100012345)}{10^{6 + 8 - 6}} \rfloor = 150018517$

In code, this final operation would entail:

```move

quote_to_match = ((base_to_match as u128) * (price as u128) / (price_shift_factor as u128) as u64);

```

Note that the `price_shift_factor` corresponds to $\large10^{(d_b + d_p - d_q)}$, which requires that the sum of base and price decimals is at least equal to the quote decimals, at least for the division operation handled above. Hence it may be more appropriate to define the more general:

* $\LARGE i_q = \lfloor i_b i_p 10^{s}\rfloor$, where $s = d_q - d_b - d_p$, such that both positive and negative $s$ values are handled.

Here, a conversion could take the form:

```move

quote_to_match = decimal_shift(base_to_match, price_shift, price_shift_sign)

```

Thus in this case an `OrderBook` would store the term `price_shift` and `price_shift_sign`.

Notably, a generic asset would assume $d_b = 0$.

**Comment by alnoki** [comment]
# API simplification

Notably, if limit orders and taker-only orders end up using the same arguments, market orders and swaps could be implemented as immediate-or-cancel orders. Here, there could be an inner function that both limit order and taker-only orders call on, with the limit order function potentially not specifying a minimum base/quote trade amounts.

**Comment by BriungRi** [comment]
I would agree that the way price currently works can lead to insufficient precision for certain markets.

What if instead of price being expressed as price per lot, it was price per indivisible base unit?

It could be easier to follow a schema like that compared to a price_decimals configuration that has to be properly accounted for per market.

**Comment by alnoki** [comment]
> What if instead of price being expressed as price per lot, it was price per indivisible base unit?

@BriungRi If I'm not mistaken, this change is intended to eliminate the internal dependency on `Coin.decimal` for both base and quote units, which is a useful simplification. But it looks like we would still need to have some notion of decimal pricing with both left and right shifting supported, unless we want to assume extreme granularity in the general case.

For example, consider the case where one indivisible base unit should only correspond to 0.005 indivisible quote units: this would entail a price of 5 and a right decimal shift of three (or a price of 50 and a right decimal shift of 4, etc.). But if on a different market one indivisible base unit should correspond to 5000 indivisible quote units, it may be more appropriate to use a price of 5000 and a shift of 0 (or a price of 500 and a left shift of 1, etc.).

We could of course account for both cases by assuming only a right decimal shift that is at minimum 0 (no shift) or, in the extreme case, a constant decimal shift of something light 10 to the right , but I wonder if perhaps this would lead to overflows for prices where one base subunit is a large number of quote subunits? E.g. a custom stable coin with 20 decimal places trading against a wrapped bitcoin variant that only has 3 decimal places.

Your thoughts?

**Comment by alnoki** [comment]
# Conventions

For a decimalized price denoting a conversion between indivisible base units and indivisible quote units, consider the following conventions:

| Term | Meaning                  |
|------|--------------------------|
| $u_b$ | Indivisible base units  |
| $u_q$ | Indivisible quote units |
| $p_d$ | Decimalized price       |
| $p_i$ | Price as an integer     |
| $e_p$ | Price exponent          |

* $\Large p_d = p_i 10^{e_p}$
* $\Large u_q = u_b p_i 10^{e_p}$
* $\Large u_b = u_b p_i 10^{-e_p}$
* $\Large p_i =\frac{u_q}{u_b} 10^{-e_p}$

For example, consider a decimalized price of 5.234 quote units per base unit ( $p_d = 5.234$ ).
Here, it may be appropriate to choose $e_p = -3$, such that $p_d = p_i 10^{-e_p} = 5234 (10^{-3})$.

Alternatively, consider a price of 123400000 quote units per base unit.
Here, it may be appropriate to choose $e_p = 5$, such that $p_d = 1234 (10^{5})$.

# Extrema

In an extreme case, consider a price where one base unit trades for $2^{64}$ quote units, the maximum number that can fit in a `u64`.
Here, $p_i = 2^{64}$ and $e_p = 0$.

Alternatively, consider a price where one quote unit trades for $2^{64}$ base units.
Here, $p_d \approx 5.42 10^{-20}$, such that $e_p$ could be chosen as -30, for example, to grant over 10 decimal places of precision.

Hence to resolve both of these extrema in a single integer with a fixed $e_p$, more than 64 bits of precision would be required in the $p_i$ significand.

# Versus Python

Python defines a decimal class with `digits` and an `exponent` field as follows:

```python
>>> from decimal import Decimal as dec
>>> dec('5.234').as_tuple()
DecimalTuple(sign=0, digits=(5, 2, 3, 4), exponent=-3)
```

Hence it may be straightforward to define a decimal price paradigm as follows:

```move

module econia::decimal {

    struct Exponent has drop, store {
        amount: u8,
        /// Irrelevant if `amount` is 0.
        is_positive: bool,
    }

    struct Decimal has drop, store {
        digits: u64,
        exponent: Exponent
    }

}

```

Then, each `OrderBook` could define a `price_exponent` field, where market prices correspond to `Decimal.digits`.
Here, a `max_decimal_digits` could be defined as `999_999_999`, for example, to ensure that prices incorporate at most 9 significant digits.
Note, as of the time of this writing the market price of `BRK.A` shares is some 482,860.00 USD, (8 significant digits), such that the proposed paradigm could resolve a `BRK.A` price of up to 9,999,999.99 USD.
Here, a 32-bit integer would be sufficient for encoding the relevant `digits`, as $2^{32}$ = `4_294_967_296`.

**Comment by alnoki** [comment]
Closing per https://github.com/econia-labs/econia-v5/blob/cb8b990/doc/architecture-specification.md#units
